# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('ingredient_type', models.CharField(choices=[(b'VE', b'Vegetable'), (b'CA', b'Carbs'), (b'BE', b'Beef'), (b'CH', b'Chicken'), (b'PO', b'Pork'), (b'MO', b'Meat_other'), (b'SA', b'Sauce'), (b'SP', b'Spice')], max_length=2)),
                ('healthyness', models.IntegerField()),
            ],
            options={
                'ordering': ('ingredient_name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('country_of_origin', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(verbose_name=b'date added')),
                ('color', models.CharField(choices=[(b'YELLOW', b'Yellow'), (b'RED', b'Red'), (b'BROWN', b'Brown'), (b'BLACK', b'Black'), (b'WHITE', b'White'), (b'GREEN', b'Green'), (b'OTHER', b'Other')], max_length=10)),
            ],
            options={
                'ordering': ('recipe_name',),
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(to='graphview.Recipe'),
        ),
    ]
