# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphview', '0002_auto_20161108_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='healthyness',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[(b'VE', b'Vegetable'), (b'CA', b'Carbs'), (b'BE', b'Beef'), (b'CH', b'Chicken'), (b'PO', b'Pork'), (b'FI', b'Fish'), (b'MO', b'Meat_other'), (b'HE', b'Herb'), (b'SP', b'Spice'), (b'DI', b'Diary'), (b'OI', b'Oil'), (b'AL', b'Alcohol'), (b'NU', b'Nuts')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='color',
            field=models.CharField(choices=[(b'YELLOW', b'Yellow'), (b'RED', b'Red'), (b'BROWN', b'Brown'), (b'BLACK', b'Black'), (b'WHITE', b'White'), (b'GREEN', b'Green'), (b'Pink', b'Pink'), (b'Orange', b'Orange'), (b'OTHER', b'Other')], max_length=10),
        ),
    ]
