# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphview', '0003_auto_20161205_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[(b'VE', b'Vegetable'), (b'CA', b'Carbs'), (b'BE', b'Beef'), (b'CH', b'Chicken'), (b'PO', b'Pork'), (b'FI', b'Fish'), (b'MO', b'Meat_other'), (b'HE', b'Herb'), (b'SP', b'Spice'), (b'DI', b'Diary'), (b'OI', b'Oil'), (b'AL', b'Alcohol'), (b'NU', b'Nuts'), (b'FR', b'Fruit')], max_length=2),
        ),
    ]
